version: "3"

services:
  php-env:
    depends_on:
      - mysql_db
    build: .
    volumes:
      - ./forum:/var/www/html
    ports:
      - "80:80"



  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - mysql_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql_db
    restart: always
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1


volumes:
  mysql_db_data: {}